name: Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup Node 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
