name: Continuous Deployment

on:
  push:
    branches:
      - master
jobs:
  pre-release-checks:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  publish-github-package-repo:
    needs: [pre-release-checks]
    runs-on: ubuntu-latest
    env:
      CI: true
      GIT_AUTHOR_NAME: 'github-actions[bot]'
      GIT_AUTHOR_EMAIL: 'github-actions[bot]@users.noreply.github.com'
      GIT_COMMITTER_NAME: 'github-actions[bot]'
      GIT_COMMITTER_EMAIL: 'github-actions[bot]@users.noreply.github.com'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 13.x
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install --ignore-engines
      - name: Build
        run: yarn build
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run semantic-release
